channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - brotli=1.1.0=h5505292_3
  - brotli-bin=1.1.0=h5505292_3
  - bsddb3=6.2.9=py311heffc1b2_5
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.2=py311h210dab8_0
  - cpython=3.11.13=py311hd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.13.6=h3818c69_3
  - debugpy=1.8.5=py311hb9542d7_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.7.0=h286801f_0
  - ffmpeg=7.1.1=gpl_h20db955_106
  - filelock=3.15.4=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py311h4921393_0
  - freetype=2.13.3=hce30654_1
  - fribidi=1.0.10=h27ca646_0
  - fsspec=2024.6.1=pyhff2d567_0
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.1.5=py311h1e33d93_1
  - graphite2=1.3.14=h286801f_0
  - harfbuzz=11.1.0=hab40de2_0
  - hdf5=1.14.3=nompi_ha698983_109
  - icu=75.1=hfee45f7_0
  - imath=3.1.12=h025cafa_0
  - importlib-metadata=8.2.0=pyha770c72_0
  - importlib_metadata=8.2.0=hd8ed1ab_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.26.0=pyh707e725_0
  - jasper=4.2.5=h743e416_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h267d04e_0
  - kiwisolver=1.4.7=py311h2c37856_0
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250127.1=cxx17_h07bc746_0
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.24.1=h493aca8_0
  - libass=0.17.3=h68e5b86_2
  - libavif16=1.3.0=hf1e31eb_0
  - libblas=3.9.0=23_osxarm64_openblas
  - libbrotlicommon=1.1.0=h5505292_3
  - libbrotlidec=1.1.0=h5505292_3
  - libbrotlienc=1.1.0=h5505292_3
  - libcblas=3.9.0=23_osxarm64_openblas
  - libcurl=8.14.1=h73640d1_0
  - libcxx=18.1.8=h5a72898_2
  - libdb=6.2.32=hbdafb3b_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h93a5062_2
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.2=h3422bc3_5
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgettextpo=0.24.1=h493aca8_0
  - libgfortran=14.2.0=heb5dd2a_105
  - libgfortran5=14.2.0=h2c44a93_105
  - libglib=2.84.0=hdff4504_0
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libiconv=1.18=hfe07756_1
  - libintl=0.24.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=23_osxarm64_openblas
  - liblapacke=3.9.0=23_osxarm64_openblas
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libnghttp2=1.64.0=h6d7220d_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libopencv=4.11.0=headless_py311h756a469_5
  - libopenvino=2025.0.0=h3f17238_3
  - libopenvino-arm-cpu-plugin=2025.0.0=h3f17238_3
  - libopenvino-auto-batch-plugin=2025.0.0=h7f72211_3
  - libopenvino-auto-plugin=2025.0.0=h7f72211_3
  - libopenvino-hetero-plugin=2025.0.0=h718ad69_3
  - libopenvino-ir-frontend=2025.0.0=h718ad69_3
  - libopenvino-onnx-frontend=2025.0.0=h1ae5b81_3
  - libopenvino-paddle-frontend=2025.0.0=h1ae5b81_3
  - libopenvino-pytorch-frontend=2025.0.0=h286801f_3
  - libopenvino-tensorflow-frontend=2025.0.0=heb6e3e1_3
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h286801f_3
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.49=h3783ad8_0
  - libprotobuf=5.29.3=hccd9074_1
  - librsvg=2.58.4=h266df6f_3
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.0=h2f21f7c_5
  - libtorch=2.7.1=cpu_generic_h5fc0106_0
  - libusb=1.0.29=hbc156a2_0
  - libuv=1.51.0=h5505292_0
  - libvorbis=1.3.7=h9f76cd9_0
  - libvpx=1.14.1=h7bae524_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.8=h52572c6_0
  - libzlib=1.3.1=hfb2fe0b_1
  - llvm-openmp=18.1.8=hde57baf_0
  - markupsafe=2.1.5=py311h05b510d_0
  - matplotlib=3.10.3=py311ha1ab1f8_0
  - matplotlib-base=3.10.3=py311h031da69_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.1=h1cfca0a_2
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hb89a1cb_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - nomkl=1.0=h5ca1d4c_0
  - opencv=4.11.0=headless_py311h62ba8ec_5
  - openexr=3.3.4=h37c74dd_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.5.2=he92f556_0
  - optree=0.16.0=py311h210dab8_0
  - pango=1.56.3=h5fd7515_1
  - parameterized=0.9.0=pyhd8ed1ab_1
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=ha881caa_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=11.2.1=py311hb9ba9e9_0
  - pip=24.2=pyhd8ed1ab_0
  - pixman=0.46.2=h2f9eb0b_0
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - pluggy=1.0.0=py311hca03da5_1
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py311hd3f4193_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-opencv=4.11.0=headless_py311h5ce6bc0_5
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pygments=2.18.0=pyhd8ed1ab_0
  - pytest=7.4.0=py311hca03da5_0
  - python=3.11.9=h932a869_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytorch=2.7.1=cpu_generic_py311_hc7d8f6d_0
  - pyzmq=26.1.0=py311h9bed540_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h92ec313_1
  - scipy=1.15.2=py311h0675101_0
  - sdl2=2.32.54=ha1acc90_0
  - sdl3=3.2.14=hf196eef_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=72.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.8=h8391f65_0
  - snappy=1.2.1=h98b9ce2_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py311h0f07fe1_0
  - svt-av1=3.0.2=h8ab69cd_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.1.0=h9541205_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.4.1=py311hd3f4193_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=16.0.0=py311h917b07b_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - zeromq=4.3.5=hcc0f68c_4
  - zipp=3.19.2=pyhd8ed1ab_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - alembic==1.16.5
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - backports-tarfile==1.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - build==1.2.1
      - certifi==2024.7.4
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - construct==2.5.3
      - datasets==2.21.0
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dill==0.3.8
      - distro==1.9.0
      - dnspython==2.6.1
      - docutils==0.21.2
      - faiss-cpu==1.8.0.post1
      - fastjsonschema==2.20.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - future==1.0.0
      - gutenberg==0.8.2
      - gutenbergpy==0.3.5
      - h11==0.14.0
      - haystack==0.42
      - httpcore==1.0.5
      - httpsproxy-urllib2==1.0
      - httpx==0.27.2
      - huggingface-hub==0.24.6
      - idna==3.7
      - ipywidgets==8.1.5
      - isodate==0.6.1
      - isoduration==20.11.0
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.2
      - jiter==0.5.0
      - json5==0.9.28
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-path==0.3.3
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keyring==25.3.0
      - langchain==0.2.16
      - langchain-core==0.2.38
      - langchain-text-splitters==0.2.4
      - langsmith==0.1.114
      - lazy-object-proxy==1.10.0
      - lcats==0.1
      - lxml==5.2.2
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - more-itertools==10.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nh3==0.2.18
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numpy==1.25.2
      - openai==1.66.3
      - openapi-core==0.19.4
      - openapi-schema-validator==0.6.2
      - openapi-spec-validator==0.7.1
      - opentelemetry-api==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - orjson==3.10.7
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parse==1.20.2
      - pathable==0.4.3
      - pefile==2024.8.26
      - pinecone-client==5.0.1
      - pinecone-plugin-inference==1.0.3
      - pinecone-plugin-interface==0.0.7
      - pkginfo==1.10.0
      - prance==23.6.21.0
      - prometheus-client==0.21.0
      - pyarrow==17.0.0
      - pybars4==0.9.13
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydantic-settings==2.4.0
      - pymeta3==0.5.1
      - pymongo==4.10.1
      - pyparsing==2.4.7
      - pyproject-hooks==1.1.0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python-ptrace==0.9.9
      - pytz==2024.1
      - pyyaml==6.0.2
      - rdflib==4.2.2
      - rdflib-sqlalchemy==0.5.4
      - readme-renderer==44.0
      - referencing==0.35.1
      - regex==2024.7.24
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986==2.0.0
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.20.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.4
      - semantic-kernel==1.8.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - sparqlwrapper==1.8.5
      - sqlalchemy==1.4.54
      - tenacity==8.5.0
      - terminado==0.18.1
      - tiktoken==0.8.0
      - tinycss2==1.4.0
      - tinydb==4.8.0
      - tokenizers==0.19.1
      - tqdm==4.66.5
      - transformers==4.44.2
      - twine==5.1.1
      - types-python-dateutil==2.9.0.20241003
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.2
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - xxhash==3.5.0
      - yarl==1.9.11
